import Foundation
import Combine

/// One SSH key discovered in `~/.ssh` (or generated by us). We don't keep our
/// own registry — the keys on disk ARE the source of truth, so this is built by
/// scanning the directory with `ssh-keygen -l`.
struct SSHKey: Identifiable, Hashable {
    var id: String { privatePath }
    var name: String            // file name, e.g. "id_ed25519"
    var privatePath: String     // absolute path to the private key
    var publicPath: String?     // absolute path to the ".pub", if present
    var type: String            // "ED25519" / "RSA" / "ECDSA" …
    var bits: Int               // key size
    var fingerprint: String     // "SHA256:…"
    var comment: String         // free-form comment baked into the key

    var hasPublicKey: Bool { publicPath != nil }
}

/// The algorithm offered when generating a new key. ed25519 is the modern
/// default; RSA-4096 is kept for older servers that don't accept ed25519.
enum SSHKeyType: String, CaseIterable, Identifiable {
    case ed25519
    case ecdsa
    case rsa
    var id: String { rawValue }

    var display: String {
        switch self {
        case .ed25519: return "Ed25519 (recommended)"
        case .ecdsa:   return "ECDSA"
        case .rsa:     return "RSA 4096"
        }
    }

    /// `ssh-keygen` arguments for the type (RSA pins a strong 4096-bit size).
    var keygenArgs: [String] {
        switch self {
        case .ed25519: return ["-t", "ed25519"]
        case .ecdsa:   return ["-t", "ecdsa", "-b", "521"]
        case .rsa:     return ["-t", "rsa", "-b", "4096"]
        }
    }
}

/// Lists, generates and deletes SSH keys in `~/.ssh`. `@MainActor` because it
/// publishes UI state; the actual `ssh-keygen` calls hop to a background process.
@MainActor
final class SSHKeyManager: ObservableObject {
    static let shared = SSHKeyManager()

    @Published private(set) var keys: [SSHKey] = []
    @Published private(set) var loading = false
    @Published var error: String?

    /// `~/.ssh` (or an isolated demo dir when launched with `--demo`).
    let sshDir = AppPaths.sshDir

    /// Files in `~/.ssh` that are never private keys.
    private let ignored: Set<String> = [
        "known_hosts", "known_hosts.old", "config", "authorized_keys",
        "environment", "rc", ".DS_Store", "agent.sock",
    ]

    private init() {}

    // MARK: - Scan

    /// Rebuild the key list from disk. A key is any file `ssh-keygen -l` can
    /// fingerprint; its public half is the sibling `.pub` when present.
    func refresh() async {
        loading = true
        defer { loading = false }
        let fm = FileManager.default
        guard let names = try? fm.contentsOfDirectory(atPath: sshDir.path) else {
            keys = []   // no ~/.ssh yet → just an empty list, not an error
            return
        }
        let candidates = names
            .filter { !$0.hasSuffix(".pub") && !ignored.contains($0) && !$0.hasPrefix(".") }
            .sorted()

        var found: [SSHKey] = []
        for name in candidates {
            let priv = sshDir.appendingPathComponent(name)
            var isDir: ObjCBool = false
            guard fm.fileExists(atPath: priv.path, isDirectory: &isDir), !isDir.boolValue else { continue }
            let pub = sshDir.appendingPathComponent("\(name).pub")
            let pubExists = fm.fileExists(atPath: pub.path)
            // Fingerprint the .pub when we have it (always works, never prompts),
            // else fall back to the private key.
            let target = pubExists ? pub.path : priv.path
            guard let info = await fingerprint(of: target) else { continue }
            found.append(SSHKey(
                name: name, privatePath: priv.path,
                publicPath: pubExists ? pub.path : nil,
                type: info.type, bits: info.bits,
                fingerprint: info.fingerprint, comment: info.comment))
        }
        keys = found
    }

    /// Parse `ssh-keygen -l -f <path>` → "256 SHA256:… comment (ED25519)".
    private func fingerprint(of path: String) async -> (bits: Int, fingerprint: String, comment: String, type: String)? {
        guard let res = try? await RemoteFileBackend.runProcess(
            "/usr/bin/ssh-keygen", ["-l", "-f", path], env: [:]), res.status == 0 else { return nil }
        let line = res.stdout.trimmingCharacters(in: .whitespacesAndNewlines)
        let tokens = line.components(separatedBy: " ").filter { !$0.isEmpty }
        guard tokens.count >= 3 else { return nil }
        let bits = Int(tokens[0]) ?? 0
        let fp = tokens[1]
        let type = tokens.last.map { $0.trimmingCharacters(in: CharacterSet(charactersIn: "()")) } ?? ""
        let comment = tokens.count > 3 ? tokens[2..<(tokens.count - 1)].joined(separator: " ") : ""
        return (bits, fp, comment, type)
    }

    // MARK: - Generate

    /// Generate a new key pair at `~/.ssh/<name>`. Fails (without prompting) if a
    /// file already exists there. `passphrase` empty = no passphrase.
    func generate(name: String, type: SSHKeyType, passphrase: String, comment: String) async -> Bool {
        error = nil
        let trimmed = name.trimmingCharacters(in: .whitespaces)
        guard !trimmed.isEmpty else { error = "Enter a name for the key."; return false }
        let path = sshDir.appendingPathComponent(trimmed)
        guard !FileManager.default.fileExists(atPath: path.path) else {
            error = "A key named “\(trimmed)” already exists."; return false
        }
        try? FileManager.default.createDirectory(at: sshDir, withIntermediateDirectories: true,
                                                 attributes: [.posixPermissions: 0o700])
        var args = type.keygenArgs
        args += ["-f", path.path, "-N", passphrase, "-C", comment, "-q"]
        guard let res = try? await RemoteFileBackend.runProcess("/usr/bin/ssh-keygen", args, env: [:]) else {
            error = "Couldn't run ssh-keygen."; return false
        }
        guard res.status == 0 else {
            error = res.stderr.isEmpty ? "Key generation failed." : res.stderr
            return false
        }
        await refresh()
        return true
    }

    // MARK: - Delete

    /// Remove a key's private + public files.
    func delete(_ key: SSHKey) {
        try? FileManager.default.removeItem(atPath: key.privatePath)
        if let pub = key.publicPath { try? FileManager.default.removeItem(atPath: pub) }
        keys.removeAll { $0.id == key.id }
    }

    /// The public key text (for "Copy public key"); nil when there's no `.pub`.
    func publicKeyText(_ key: SSHKey) -> String? {
        guard let pub = key.publicPath else { return nil }
        return (try? String(contentsOfFile: pub, encoding: .utf8))?
            .trimmingCharacters(in: .whitespacesAndNewlines)
    }
}
