//! SSH key discovery, generation and deletion in `~/.ssh` — the portable Zig
//! port of SSHKeys.swift (SSHKeyManager). We keep no registry of our own: the
//! files on disk ARE the source of truth, so the list is built by scanning the
//! directory and fingerprinting each key with `ssh-keygen -l`.
//!
//! The parsing (parseKeygenList) is pure and unit-tested; the disk/process
//! bits shell out to the same OpenSSH tool the macOS app uses.

const std = @import("std");

/// One SSH key discovered in `~/.ssh` (or generated by us). All slices are
/// owned by the surrounding allocation (arena for `list`, caller for the
/// pure parser).
pub const KeyInfo = struct {
    /// File name of the private key, e.g. "id_ed25519".
    name: []const u8,
    /// Absolute path to the private key.
    path: []const u8,
    /// "ED25519" / "RSA" / "ECDSA" …
    keyType: []const u8,
    /// Key size in bits.
    bits: u32,
    /// "SHA256:…" fingerprint.
    fingerprint: []const u8,
    /// Free-form comment baked into the key ("" when absent).
    comment: []const u8,
    hasPrivate: bool,
    hasPublic: bool,
};

/// The parsed fields of a single `ssh-keygen -l` line.
pub const KeygenLine = struct {
    bits: u32,
    fingerprint: []const u8,
    comment: []const u8,
    keyType: []const u8,
};

/// The algorithm offered when generating a new key.
pub const KeyType = enum { ed25519, ecdsa, rsa };

/// Options for `generate`. `bits` is optional; when null the default for the
/// type is used (`-b` is omitted, letting ssh-keygen pick). `passphrase` may
/// be empty for a no-passphrase key.
pub const GenerateOptions = struct {
    type: KeyType,
    bits: ?u32 = null,
    path: []const u8,
    passphrase: []const u8 = "",
    comment: []const u8 = "",
};

/// Result of a `list` scan. Arena-backed; call `deinit` when done.
pub const Loaded = struct {
    arena: std.heap.ArenaAllocator,
    keys: []KeyInfo,

    pub fn deinit(self: *Loaded) void {
        self.arena.deinit();
    }
};

/// Files in `~/.ssh` that are never private keys.
const ignored = [_][]const u8{
    "known_hosts", "known_hosts.old", "config",  "authorized_keys",
    "environment", "rc",             ".DS_Store", "agent.sock",
};

/// Parse a single `ssh-keygen -l -f <file>` output line. Format is:
///   `<bits> <fingerprint> <comment> (<TYPE>)`
/// The comment is everything between the fingerprint and the trailing
/// `(TYPE)` token, and may contain spaces or be empty. Returns null when the
/// line doesn't have at least `<bits> <fingerprint> (<TYPE>)`.
///
/// Slices point into `line` — no allocation; the result borrows the input.
pub fn parseKeygenList(line: []const u8) ?KeygenLine {
    const trimmed = std.mem.trim(u8, line, &std.ascii.whitespace);
    if (trimmed.len == 0) return null;

    // bits: leading run of digits, terminated by the first space.
    const first_space = std.mem.indexOfScalar(u8, trimmed, ' ') orelse return null;
    const bits = std.fmt.parseInt(u32, trimmed[0..first_space], 10) catch return null;

    // fingerprint: the next whitespace-delimited token.
    const after_bits = std.mem.trimLeft(u8, trimmed[first_space..], " ");
    const fp_end = std.mem.indexOfScalar(u8, after_bits, ' ') orelse return null;
    const fingerprint = after_bits[0..fp_end];
    if (fingerprint.len == 0) return null;

    // type: the last parenthesized token. Strip the surrounding "()".
    const last_space = std.mem.lastIndexOfScalar(u8, trimmed, ' ') orelse return null;
    const last_tok = trimmed[last_space + 1 ..];
    const keyType = std.mem.trim(u8, last_tok, "()");
    if (keyType.len == 0) return null;

    // comment: everything between the fingerprint and the trailing type,
    // trimmed of the surrounding whitespace. Empty when the two touch (e.g.
    // ssh-keygen emits "no comment" as the comment, or nothing at all).
    const comment_start = fp_end; // relative to after_bits, points at the space after fp
    const comment_region_start = (after_bits.ptr - trimmed.ptr) + comment_start;
    // When the fingerprint token is immediately followed by `(TYPE)` there is
    // no comment; guard against the region running past the trailing space.
    const comment_raw = if (comment_region_start < last_space)
        trimmed[comment_region_start..last_space]
    else
        "";
    const comment = std.mem.trim(u8, comment_raw, &std.ascii.whitespace);

    return .{
        .bits = bits,
        .fingerprint = fingerprint,
        .comment = comment,
        .keyType = keyType,
    };
}

/// `~/.ssh` as an absolute path. Caller owns the result. Falls back to a
/// bare ".ssh" when $HOME is unset.
pub fn sshDir(alloc: std.mem.Allocator) ![]u8 {
    const home = std.posix.getenv("HOME") orelse return alloc.dupe(u8, ".ssh");
    return std.fs.path.join(alloc, &.{ home, ".ssh" });
}

fn isIgnored(name: []const u8) bool {
    if (name.len > 0 and name[0] == '.') return true;
    for (ignored) |ig| {
        if (std.mem.eql(u8, name, ig)) return true;
    }
    return false;
}

/// Run `ssh-keygen -l -f <path>` and parse its single output line. Returns
/// null on any failure (non-zero exit, unparseable output). The returned
/// slices are freshly allocated in `alloc` (independent of the input path).
fn fingerprintFile(alloc: std.mem.Allocator, path: []const u8) ?KeygenLine {
    var child = std.process.Child.init(
        &.{ "ssh-keygen", "-l", "-f", path },
        alloc,
    );
    child.stdout_behavior = .Pipe;
    child.stderr_behavior = .Ignore;
    child.spawn() catch return null;
    const out = child.stdout.?.readToEndAlloc(alloc, 64 * 1024) catch {
        _ = child.wait() catch {};
        return null;
    };
    const term = child.wait() catch return null;
    switch (term) {
        .Exited => |code| if (code != 0) return null,
        else => return null,
    }
    // First non-empty line of output.
    var it = std.mem.splitScalar(u8, out, '\n');
    while (it.next()) |raw| {
        if (std.mem.trim(u8, raw, &std.ascii.whitespace).len == 0) continue;
        return parseKeygenList(raw);
    }
    return null;
}

/// Scan `~/.ssh` and return every discoverable key. A key is any non-ignored
/// file `ssh-keygen -l` can fingerprint; its public half is the sibling
/// `.pub`. We fingerprint the `.pub` when present (never prompts), else the
/// private key. A missing `~/.ssh` yields an empty list, not an error. The
/// result is arena-backed — call `.deinit()`.
pub fn list(gpa: std.mem.Allocator) !Loaded {
    var arena: std.heap.ArenaAllocator = .init(gpa);
    errdefer arena.deinit();
    const alloc = arena.allocator();

    const dir_path = try sshDir(alloc);

    var dir = std.fs.cwd().openDir(dir_path, .{ .iterate = true }) catch |err| switch (err) {
        error.FileNotFound, error.NotDir => return .{ .arena = arena, .keys = &.{} },
        else => return err,
    };
    defer dir.close();

    // Collect candidate private-key names (everything that isn't a .pub or
    // an ignored file), and the set of .pub names for public-half detection.
    var privates: std.ArrayList([]const u8) = .empty;
    var pubs: std.StringHashMapUnmanaged(void) = .empty;

    var it = dir.iterate();
    while (try it.next()) |entry| {
        if (entry.kind == .directory) continue;
        if (std.mem.endsWith(u8, entry.name, ".pub")) {
            try pubs.put(alloc, try alloc.dupe(u8, entry.name), {});
            continue;
        }
        if (isIgnored(entry.name)) continue;
        try privates.append(alloc, try alloc.dupe(u8, entry.name));
    }

    std.mem.sort([]const u8, privates.items, {}, lessThanStr);

    var keys: std.ArrayList(KeyInfo) = .empty;
    for (privates.items) |name| {
        const priv_path = try std.fs.path.join(alloc, &.{ dir_path, name });
        const pub_name = try std.fmt.allocPrint(alloc, "{s}.pub", .{name});
        const has_public = pubs.contains(pub_name);
        const target = if (has_public)
            try std.fs.path.join(alloc, &.{ dir_path, pub_name })
        else
            priv_path;

        const info = fingerprintFile(alloc, target) orelse continue;
        try keys.append(alloc, .{
            .name = name,
            .path = priv_path,
            .keyType = try alloc.dupe(u8, info.keyType),
            .bits = info.bits,
            .fingerprint = try alloc.dupe(u8, info.fingerprint),
            .comment = try alloc.dupe(u8, info.comment),
            .hasPrivate = true,
            .hasPublic = has_public,
        });
    }

    return .{ .arena = arena, .keys = try keys.toOwnedSlice(alloc) };
}

fn lessThanStr(_: void, a: []const u8, b: []const u8) bool {
    return std.mem.lessThan(u8, a, b);
}

/// Generate a new key pair with `ssh-keygen`. Spawns:
///   `ssh-keygen -t <type> [-b <bits>] -f <path> -N <passphrase> -C <comment> -q`
/// An empty passphrase is passed as an empty `-N` argument (no passphrase).
/// Returns true on a zero exit code. Does not overwrite: ssh-keygen itself
/// refuses when the file exists (and we pass `-q`, so it won't prompt — an
/// existing file is reported via a non-zero exit).
pub fn generate(alloc: std.mem.Allocator, opts: GenerateOptions) !bool {
    var argv: std.ArrayList([]const u8) = .empty;
    defer argv.deinit(alloc);

    // -b buffer must outlive the spawn; allocate when used.
    var bits_buf: [16]u8 = undefined;

    try argv.append(alloc, "ssh-keygen");
    try argv.append(alloc, "-t");
    try argv.append(alloc, @tagName(opts.type));
    if (opts.bits) |b| {
        const s = std.fmt.bufPrint(&bits_buf, "{d}", .{b}) catch return error.InvalidBits;
        try argv.append(alloc, "-b");
        try argv.append(alloc, s);
    }
    try argv.append(alloc, "-f");
    try argv.append(alloc, opts.path);
    try argv.append(alloc, "-N");
    try argv.append(alloc, opts.passphrase); // empty slice == -N ""
    try argv.append(alloc, "-C");
    try argv.append(alloc, opts.comment);
    try argv.append(alloc, "-q");

    var child = std.process.Child.init(argv.items, alloc);
    child.stdin_behavior = .Ignore;
    child.stdout_behavior = .Ignore;
    child.stderr_behavior = .Ignore;
    try child.spawn();
    const term = try child.wait();
    return switch (term) {
        .Exited => |code| code == 0,
        else => false,
    };
}

/// Delete a key's private and public (`.pub`) files from disk. A missing
/// file is not an error (idempotent).
pub fn delete(alloc: std.mem.Allocator, path: []const u8) !void {
    std.fs.cwd().deleteFile(path) catch |err| switch (err) {
        error.FileNotFound => {},
        else => return err,
    };
    const pub_path = try std.fmt.allocPrint(alloc, "{s}.pub", .{path});
    defer alloc.free(pub_path);
    std.fs.cwd().deleteFile(pub_path) catch |err| switch (err) {
        error.FileNotFound => {},
        else => return err,
    };
}

test "sarv: parseKeygenList parses a basic ed25519 line" {
    const r = parseKeygenList("256 SHA256:abc123def comment@host (ED25519)").?;
    try std.testing.expectEqual(@as(u32, 256), r.bits);
    try std.testing.expectEqualStrings("SHA256:abc123def", r.fingerprint);
    try std.testing.expectEqualStrings("comment@host", r.comment);
    try std.testing.expectEqualStrings("ED25519", r.keyType);
}

test "sarv: parseKeygenList keeps a multi-word comment" {
    const r = parseKeygenList("3072 SHA256:xyz no comment here (RSA)").?;
    try std.testing.expectEqual(@as(u32, 3072), r.bits);
    try std.testing.expectEqualStrings("SHA256:xyz", r.fingerprint);
    try std.testing.expectEqualStrings("no comment here", r.comment);
    try std.testing.expectEqualStrings("RSA", r.keyType);
}

test "sarv: parseKeygenList handles the (no comment) sentinel" {
    // ssh-keygen prints the literal words "no comment" as the comment when a
    // key has none. We faithfully return whatever sits between fp and (TYPE).
    const r = parseKeygenList("256 SHA256:qqq no comment (ED25519)").?;
    try std.testing.expectEqualStrings("no comment", r.comment);
    try std.testing.expectEqualStrings("ED25519", r.keyType);
}

test "sarv: parseKeygenList handles an empty comment" {
    // No comment token at all: `<bits> <fp> (<TYPE>)`.
    const r = parseKeygenList("521 SHA256:eee (ECDSA)").?;
    try std.testing.expectEqual(@as(u32, 521), r.bits);
    try std.testing.expectEqualStrings("SHA256:eee", r.fingerprint);
    try std.testing.expectEqualStrings("", r.comment);
    try std.testing.expectEqualStrings("ECDSA", r.keyType);
}

test "sarv: parseKeygenList tolerates surrounding and extra whitespace" {
    const r = parseKeygenList("  4096   SHA256:mmm   my key   (RSA)  ").?;
    try std.testing.expectEqual(@as(u32, 4096), r.bits);
    try std.testing.expectEqualStrings("SHA256:mmm", r.fingerprint);
    try std.testing.expectEqualStrings("my key", r.comment);
    try std.testing.expectEqualStrings("RSA", r.keyType);
}

test "sarv: parseKeygenList rejects malformed lines" {
    try std.testing.expect(parseKeygenList("") == null);
    try std.testing.expect(parseKeygenList("   ") == null);
    try std.testing.expect(parseKeygenList("notanumber SHA256:x c (RSA)") == null);
    try std.testing.expect(parseKeygenList("256") == null); // no fingerprint/type
}

test "sarv: sshDir ends with .ssh" {
    const alloc = std.testing.allocator;
    const p = try sshDir(alloc);
    defer alloc.free(p);
    try std.testing.expect(std.mem.endsWith(u8, p, ".ssh"));
}
